name: SCKillTracker Client Build and Release

on:
  push:
    tags:
      - 'v*'   # Runs whenever you push a tag like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --clean -F ^
            --name "sckilltracker_client" ^
            --icon "static/sckticon.ico" ^
            --add-data "templates;templates" ^
            --add-data "static;static" ^
            --add-data "src;src" ^
            app.py --uac-admin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sckilltracker_client
          path: dist/sckilltracker_client.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: sckilltracker_client
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: sckilltracker_client.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}